# Generated by Django 4.0.4 on 2022-05-10 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsmanger',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
