# Generated by Django 4.0.4 on 2022-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanger', '0002_alter_passwordsmanger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsmanger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
